{
    'name': 'Billiard Club',
    'version': '15.0.1.0',
    'application': True,
    'installable': True,
    'depends': ['base', 'mail'],
    'data': ['security/groups.xml',
             'security/ir.model.access.csv',
             'views/x_player_view.xml',
             'views/x_league_view.xml',
             'views/report.xml',
             'views/x_match_detail_view.xml',
             'views/x_match.xml',
             'views/x_team_view.xml',
             'views/x_league_type_view.xml',
             'views/x_fee_view.xml',
             'views/x_player_menu.xml',
             'views/x_fund.xml',
             'views/x_budget.xml',
             'views/x_standing.xml',
             ],
    'license': 'GPL-3',
}
